from time import sleep

print('PERMAINAN RPG')
data = input('Start? y/n')
if(data == 'y'):
    print('Oke lets go')
    sleep(2)
    print('...')
    sleep(2)
    print('hari yang indah..')
    sleep(2)
    print('ada kolam, pohon pohon')
    data = input('apa yg mau kamu lakukan menebang atau memancing? fish/chop')
    if(data == 'fish'):
        print('kamu mengambil tas mu..')
        sleep(2)
        print('oh tidak kamu tidak membawa alat pemancing')
        sleep(1)
        print('kita harus beli dulu!.. ')
        sleep(3)
        print('kamu tiba di perkotaan')
        sleep(2)
        print('')
        print('kamu pun memasuki salah satu toko peralatan di sana..\n')
        sleep(2)
        print('"Assalamualaikum..."')
        sleep(2)
        print('"Mau beli alat mancing 1"')
        sleep(2)
        print('sekalian sama  bait nya 6 deh"')
        sleep(2)
        print("'OOKE'")
        sleep(1)
        print('Dia pun mencari alat mancing dan baitnya')
        sleep(3)
        print("'INI DIA'")
        sleep(1)
        print('"oke makasih"')
        sleep(2)
        print('kamu pun kembali ke dalam hutan ')
        sleep(2)
        print('"Akhirnya aku bisa mancing yey"')
        sleep(3)
        print('kamu pun manciing...')
        sleep(2)
        print('"aku harus hoki nih"')
        sleep(2)
        data = input('m/n')
        if(data == 'm'):
            print('cringgg!')
            sleep(2)
            print('kamu pun GAGAL mendapatkan ikan wkwkwkw')
            sleep(2)
            print('haha tidak apa besok mancing lagi ya')
            sleep(2)
            print('cs..cs..cs')
            sleep(2)
            print('"APA..An tuh.."')
            sleep(2)
            print('suara itu terdengar dari semak semak')
            sleep(2)
            print('kamu pun mendekati semak semak nya')
            sleep(2)
            print('itu ternyata hanya kucing hutan')
            sleep(2)
            print('"huu... kukira apa"')
            sleep(2)
            print('"Hari sudah mulai gelap.. pulang ah"')
            sleep(2)
            print('Kamu pun pulang..')
            sleep(1)
            print('.')
            sleep(1)
            print('.')
            sleep(2)
            print('kamu sampai rumah')
            sleep(2)
            print('"Assalamualaikum"')
            sleep(2)
            print('ternyata dirumah gak ada orang ')
            sleep(2)
            data = input('"mau makan atau nyantai dulu ya?" sans/makan')
            if(data == 'sans'):
                print('kamu pun sanstai')
                sleep(2)
                print('dududu~~')
                sleep(2)
                print('eh apaan tuh?')
                sleep(2)
                print('wadah game baru')
                sleep(2)
                print('main dulu ahh')
                sleep(1)
                print('DUAR')
                sleep(1)
                print('SZIIING')
                sleep(1)
                print('entah kenapa kamu masuk ke sebuah dimensi lain!')
                sleep(2)
                print('BER..SAM..BUNG~')

            if(data == 'makan'):
                print('"Makan ah "')
                sleep(2)
                print('nyam nyam~~')
                sleep(2)
                print('Tiba tiba ada yang ngetok pintu')
                sleep(2)
                print('"IYA... BENTAR.."')
                sleep(2)
                print('pas kamu buka')
                sleep(1)
                print('TIBA TIBA DIA MENCULIK KAMU!')
                sleep(2)
                print('BERSAMBUNG...')

        if(data == 'n'):
            print('Kamu Memancing denggan kehokian huruf N')
            sleep(2)
            print('CRING!')
            sleep(2)
            print('Kamu Pun Mendapatkan KEHOKIAN')
            sleep(2)
            print('Kamu Mendapat ikan yeey')
            sleep(2)
            print('"Alhamdullillah"')
            sleep(1)
            print('kamu pun pulang ke rumah karena udah mulai gelap')
            sleep(2)
            print('di pertengahan jalan kamu melihat seekor kucing yang sangat lucu')
            sleep(2)
            data = input('kamu kan punya ikan mau ngasih kekucingnya gak? y/n')
            if(data == 'y'):
                print('yeee')
                sleep(2)
                print('kamu mengasih ikan pada kucing')
                sleep(2)
                print('Tiba Tiba')
                sleep(2)
                print("DENGAN KEHOKIAN HURUF N \n DAN KE LUCUAN KUCING....")
                sleep(2)
                print('\nKAMU PUN MENDAPAT KEKUATAN!')
                sleep(1)
                print('THE END')
                sleep(2)
                print('JK')
                sleep(2)
                print('COMING SOON-->-->')
            if(data == 'n'):
                print('yaah')
                sleep(2)
                print('si kucing sad')
                sleep(2)
                print('tiba tiba')
                sleep(2)
                print("DENGAN KEHOKIAN HURUF N YANG TIDAK MAU DI BAGI")
                sleep(2)
                print('kamu pun pingssan dan dibawa ke ruang hukuman HURUF N')
                sleep(2)
                print('BERSAMBUNG...')
    if(data == 'chop'):
        print('kamu pun mengambil perakatan di tas yang sudah di siapkan')
