from time import sleep

print('PERMAINAN RPG')
data = input('Start? y')
if(data == 'y'):
    print('\nOke lets go')
    sleep(2)
    print('...')
    sleep(2)
    print('hari yang indah..')
    sleep(2)
    print('ada kolam, pohon pohon')
    data = input('apa yg mau kamu lakukan menebang atau memancing? fish/chop')
    if(data == 'fish'):
        print('kamu mengambil tas mu..')
        sleep(2)
        print('oh tidak kamu tidak membawa alat pemancing')
        sleep(1)
        print('kita harus beli dulu!.. ')
        sleep(3)
        print('kamu tiba di perkotaan')
        sleep(2)
        print('')
        print('kamu pun memasuki salah satu toko peralatan di sana..\n')
        sleep(2)
        print('"Assalamualaikum..."')
        sleep(2)
        print('"Mau beli alat mancing 1"')
        sleep(2)
        print('"sekalian sama  bait nya 6 deh"')
        sleep(2)
        print("'OOKE'")
        sleep(1)
        print('Dia pun mencari alat mancing dan baitnya')
        sleep(3)
        print("'INI DIA'")
        sleep(1)
        print('"oke makasih"')
        sleep(2)
        print('\n==kamu pun kembali ke dalam hutan== ')
        sleep(2)
        print('"Akhirnya aku bisa mancing yey"')
        sleep(3)
        print('kamu pun manciing...')
        sleep(2)
        print('"aku harus hoki nih"\n')
        sleep(2)
        data = input('m/n  ')
        if(data == 'm'):
            print('cringgg!')
            sleep(2)
            print('kamu pun GAGAL mendapatkan ikan wkwkwkw')
            sleep(2)
            print('haha tidak apa besok mancing lagi ya')
            sleep(2)
            print('cs..cs..cs')
            sleep(2)
            print('"APA..An tuh.."')
            sleep(2)
            print('suara itu terdengar dari semak semak')
            sleep(2)
            print('kamu pun mendekati semak semak nya')
            sleep(2)
            print('itu ternyata hanya kucing hutan')
            sleep(2)
            print('"huu... kukira apa"')
            sleep(2)
            print('"Hari sudah mulai gelap.. pulang ah"')
            sleep(2)
            print('Kamu pun pulang..')
            sleep(1)
            print('.')
            sleep(1)
            print('.')
            sleep(2)
            print('kamu sampai rumah')
            sleep(2)
            print('"Assalamualaikum"')
            sleep(2)
            print('ternyata dirumah gak ada orang ')
            sleep(2)
            data = input('"mau makan atau nyantai dulu ya?" sans/makan')
            if(data == 'sans'):
                print('kamu pun sanstai')
                sleep(2)
                print('dududu~~')
                sleep(2)
                print('eh apaan tuh?')
                sleep(2)
                print('wadah game baru')
                sleep(2)
                print('main dulu ahh')
                sleep(1)
                print('DUAR')
                sleep(1)
                print('SZIIING')
                sleep(1)
                print('entah kenapa kamu masuk ke sebuah dimensi lain!')
                sleep(2)
                print('BER..SAM..BUNG~')

            elif(data == 'makan'):
                print('"Makan ah "')
                sleep(2)
                print('nyam nyam~~')
                sleep(2)
                print('Tiba tiba ada yang ngetok pintu')
                sleep(2)
                print('"IYA... BENTAR.."')
                sleep(2)
                print('pas kamu buka')
                sleep(1)
                print('TIBA TIBA DIA MENCULIK KAMU!')
                sleep(2)
                print('BERSAMBUNG...')
            
            else:
                print('COMMAND TIDAK DITEMUKAN ULANG DARI AWAL')

        elif(data == 'n'):
            print('Kamu Memancing denggan kehokian huruf N')
            sleep(2)
            print('CRING!')
            sleep(2)
            print('Kamu Pun Mendapatkan KEHOKIAN')
            sleep(2)
            print('Kamu Mendapat ikan yeey')
            sleep(2)
            print('"Alhamdullillah"')
            sleep(1)
            print('kamu pun pulang ke rumah karena udah mulai gelap')
            sleep(2)
            print('di pertengahan jalan kamu melihat seekor kucing yang sangat lucu')
            sleep(2)
            data = input('kamu kan punya ikan mau ngasih kekucingnya gak? y/n')
            if(data == 'y'):
                print('yeee')
                sleep(2)
                print('kamu mengasih ikan pada kucing')
                sleep(2)
                print('Tiba Tiba')
                sleep(2)
                print("DENGAN KEHOKIAN HURUF N \n DAN KE LUCUAN KUCING....")
                sleep(2)
                print('\nKAMU PUN MENDAPAT KEKUATAN!')
                sleep(1)
                print('THE END')
                sleep(2)
                print('JK')
                sleep(2)
                print('COMING SOON-->-->')
                sleep(2)
                print('GOOD ENDING..--``')
                sleep(2)
                print('UNTUK SAAT INI->->->')
            elif(data == 'n'):
                print('yaah')
                sleep(2)
                print('si kucing sad')
                sleep(2)
                print('tiba tiba')
                sleep(2)
                print("DENGAN KEHOKIAN HURUF N YANG TIDAK MAU DI BAGI")
                sleep(2)
                print('kamu pun pingssan dan dibawa ke ruang hukuman HURUF N')
                sleep(2)
                print('BERSAMBUNG...')
                sleep(2)
                print('BAD ENDING...')
                sleep(2)
                print('UNTUK SAAT INI...')

            else:
                print('COMMAND TIDAK DITEMUKAN ULANG DARI AWAL')

        else:
            print('COMMAND TIDAK DITEMUKAN ULANG DARI AWAL')
    elif(data == 'chop'):
        print('kamu pun mengambil peralatan di tas yang sudah di siapkan')
        sleep(2)
        print('kamu mengambil kapak yang ada di tas perlengkapan')
        sleep(2)
        data = input('Mau langsung nebang pohon? y/n')
        if(data == 'y'):
            print('"langsung tebang pohon ajalah"')
            sleep(2)
            print('pohon ditebang~')
            sleep(2)
            print('Tuk.. Tuk..')
            sleep(2)
            print('ckreek....')
            sleep(2)
            print('pohon pun jatuh')
            sleep(2)
            print('"nice"')
            sleep(2)
            data = input('mau di apakan? chop/sell')
            if(data == "sell"):
                print('kamu pun menjual kayu tersebut dengan harga 200 rb')
                sleep(2)
                print('kamu mendapat 200 rb')
                sleep(2)
                data = input('kamu mau apakan duitnya?\nBeli makan(b), atau di tabung(a)')
                if(data == 'b'):
                    print('\n\nkamu menuju ke salah satu toko di kota')
                    sleep(2)
                    print('yang pasti...')
                    sleep(2)
                    print('=====TOKO MAKANAN=====')
                    sleep(2)
                    print('kamu pun menuju ke kasir')
                    sleep(2)
                    print('"Assalamualaikum, mba pesen paha ayam satu"')
                    sleep(2)
                    print("'Oke Tunggu Ya~'")
                    sleep(2)
                    print('"oke"')
                    sleep(2)
                    print('kamu pun menuju ke salah satu meja yang kosong')
                    sleep(2)
                    print('kamu menunggu agak lama')
                    sleep(1)
                    print('"Aduh gabut"')
                    sleep(2)
                    print('kamu pun buka hp')
                    sleep(2)
                    print('ada yang nelpon tiba tiba')
                    sleep(2)
                    print('makanannya sampai')
                    sleep(2)
                    print('di telpon nya gak ada yg ngomong')
                    sleep(2)
                    print('mau di matikan atau nanya? m/n')
                    sleep(1)
                    data = input('')
                    if(data == 'm'):
                        print('\nkamuu pun mematikan hpnya')
                        sleep(2)
                        print('kamu pun makan dengan tenang..')
                        sleep(2)
                        print('.....')
                        sleep(2)
                        print('nyam nyam..')
                        sleep(1)
                        print('nyam')
                        sleep(2)
                        print('"duh haus"')
                        sleep(2)
                        print('kamu pun mau mengambil minuman di dalam tas')
                        sleep(2)
                        print('setelah kamu melihat ke bawah untuk mengambil minuman dari tas')
                        sleep(3)
                        print('kamu melihat tas nya MENGHILANG!')
                        sleep(2)
                        print('kamu pun panik karena nya')
                        sleep(2)
                        print('BERSAMBUNG....')
                        sleep(2)
                        print('<><>A Confusing Ending<><>') 
                    elif(data == 'n'):
                        print('kamu pun menanyakan sesuatu')
                        sleep(2)
                        print('"Oi Kenapa kamu nelpon aku?"')
                        sleep(2)                         
                        print('"Kok kamu bisa tau nomer aku?"')
                        sleep(2)
                        print('"HALO??"')
                        sleep(2)
                        print("'tz...tz.. to..'")
                        sleep(2)
                        print("'long....tz..tz'")
                        sleep(2)
                        print('"HAH?!"')
                        sleep(0.5)
                        print('BERSAMBUNG')
                        sleep(0.4)
                        print('<><>A Confusing Ending<><>')     
                        sleep(0.5)
                        print('.')
                        sleep(0.7)
                        print('_')
                        sleep(1)
                        print('.')
                        sleep(1)
                        print('-')
                    else:
                        print('COMMAND TIDAK DITEMUKAN ULANG DARI AWAL!')

                elif(data == 'a'):
                    print('\nkamu pun menuju ke rumah')
                    sleep(2)
                    print('saat perjalan pulang')
                    sleep(2)
                    print('kamu melihat ada kucing di jalan')
                    sleep(2)
                    data = input('kamu mau elus? y/n')
                    if(data == 'y'):
                        print('kamu menghampiri kucing itu')
                        sleep(2)
                        print('kamu mengelus nya :D')
                        sleep(2)
                        print('kamu pun pulang')
                        sleep(2)
                        print('...')
                        sleep(2)
                        print('kamu sampai rumah...')
                        sleep(2)
                        print('kamu laper dan makan')
                        sleep(2)
                        print('kamu ngambil nasi untuk makan ayam')
                        sleep(2)
                        print('kamu pun makan dengan tenang..')
                        sleep(2)
                        print('nyam nyam....')
                        sleep(2)
                        print('dan tiba tiba ada kucing..')
                        sleep(2)
                        print('Meow....Meow..')
                        sleep(2)
                        print('BERSAMBUNG/..../')
                        sleep(2)
                        print('WAIT A MINUTE...??')
                        sleep(2)
                    if(data == 'n'):
                        print('Kamu pun gas aja langsung ke rumah')
                        sleep(2)
                        print('....')
                        sleep(2)
                        print('kamu sampai rumah..')
                        sleep(2)
                        print('kamu mau makan')
                        sleep(2)
                        print('tapi kok ga ada makanan')
                        sleep(2)
                        print('"Huft gak ada makanan. mending aku beli online aja"')
                        sleep(2)
                        print('kamu pun membeli makan lewat online')
                        sleep(2)
                        print('...')
                        sleep(2)
                        print('"makanannya kok lama sih"')
                        sleep(2)
                        print('"padahal lagi laper"')
                        sleep(2)
                        print('"Tidur ajalah bodo amat"')
                        sleep(2)
                        print('dan... BerSamBung...')
                        sleep(2)
                        print('A Confusing Ending')
                        sleep(2)
                else:
                    print('COMMAND TIDAK DITEMUKAN ULANG DARI AWAL!')




            print('suara itu terdengar dari semak semak')
            sleep(2)
            print('kamu pun mendekati semak semak nya')
            sleep(2)
            print('itu ternyata hanya kucing hutan')
            sleep(2)
            print('"huu... kukira apa"')
            sleep(2)
            print('"Hari sudah mulai gelap.. pulang ah"')
            sleep(2)
            print('Kamu pun pulang..')
            sleep(1)
            print('.')
            sleep(1)
            print('.')
            sleep(2)
            print('kamu sampai rumah')
            sleep(2)
            print('"Assalamualaikum"')
            sleep(2)
            print('ternyata dirumah gak ada orang ')
            sleep(2)
            data = input('"mau makan atau nyantai dulu ya?" sans/makan')
            if(data == 'sans'):
                print('kamu pun sanstai')
                sleep(2)
                print('dududu~~')
                sleep(2)
                print('eh apaan tuh?')
                sleep(2)
                print('wadah game baru')
                sleep(2)
                print('main dulu ahh')
                sleep(1)
                print('DUAR')
                sleep(1)
                print('SZIIING')
                sleep(1)
                print('entah kenapa kamu masuk ke sebuah dimensi lain!')
                sleep(2)
                print('BER..SAM..BUNG~')

            if(data == 'makan'):
                print('"Makan ah "')
                sleep(2)
                print('nyam nyam~~')
                sleep(2)
                print('Tiba tiba ada yang ngetok pintu')
                sleep(2)
                print('"IYA... BENTAR.."')
                sleep(2)
                print('pas kamu buka')
                sleep(1)
                print('TIBA TIBA DIA MENCULIK KAMU!')
                sleep(2)
                print('BERSAMBUNG...')

        if(data == 'n'):
            print('Kamu Memancing denggan kehokian huruf N')
            sleep(2)
            print('CRING!')
            sleep(2)
            print('Kamu Pun Mendapatkan KEHOKIAN')
            sleep(2)
            print('Kamu Mendapat ikan yeey')
            sleep(2)
            print('"Alhamdullillah"')
            sleep(1)
            print('kamu pun pulang ke rumah karena udah mulai gelap')
            sleep(2)
            print('di pertengahan jalan kamu melihat seekor kucing yang sangat lucu')
            sleep(2)
            data = input('kamu kan punya ikan mau ngasih kekucingnya gak? y/n')
            if(data == 'y'):
                print('yeee')
                sleep(2)
                print('kamu mengasih ikan pada kucing')
                sleep(2)
                print('Tiba Tiba')
                sleep(2)
                print("DENGAN KEHOKIAN HURUF N \n DAN KE LUCUAN KUCING....")
                sleep(2)
                print('\nKAMU PUN MENDAPAT KEKUATAN!')
                sleep(1)
                print('THE END')
                sleep(2)
                print('JK')
                sleep(2)
                print('COMING SOON-->-->')
            if(data == 'n'):
                print('yaah')
                sleep(2)
                print('si kucing sad')
                sleep(2)
                print('tiba tiba')
                sleep(2)
                print("DENGAN KEHOKIAN HURUF N YANG TIDAK MAU DI BAGI")
                sleep(2)
                print('kamu pun pingssan dan dibawa ke ruang hukuman HURUF N')
                sleep(2)
                print('BERSAMBUNG...')
    if(data == 'chop'):
        print('kamu pun mengambil perakatan di tas yang sudah di siapkan')
