from time import sleep
data = input('START GAME? y/n')
if(data == 'y'):
    print("OKEY")
    sleep(2)
    print('Mau milih mobil yang mana?')
    sleep(1)
    print('1.Mobilnya cepet banget\n2.Mobilnya gak cepet tapi kuat banget')
    data = int(input('1/2'))
    if(data == 1):
        print("\n\nBrooom......")
        sleep(2)
        print('MOBIL PALING CEPAT')
        sleep(2)
        print('\n\nLet')
        sleep(1)
        print('\nSet')
        sleep(2)
        print('GO!')
        sleep(0.5)
        print('BROOOOOM.....')
        sleep(1)
        print('broom.~.~broom')
        sleep(2)
        print('oh tidak ada yg mau nyelip dari kanan coy')
        sleep(1)
        data = input('mau gas atau ke kanan? g/k')
        if(data == 'g'):
            print('\n\nBROOOOOOM~~~~~!')
            sleep(2)
            print('kamu pun menempati Posisi 1')
            sleep(1)
            print('pembalap lain juga tidak bisa mengejar kamu yey')
            sleep(2)
            print('Gariis Finish Di DEPAN!')
            sleep(1)
            print('dannn... kamu MENANG DENGAN MENEMATI JUARA 1 YEY!')
            sleep(2)
            print('GOOD ENDING :)')
        if(data == 'k'):
            print("\n\nSHHHH~~")
            sleep(2)
            print('kamu pun belok ke kanan')
            sleep(2)
            print('oh tidak kamu DITABRAK!')
            sleep(1)
            print('kamu pun terluka dan mobilnya pun hancur')
            sleep(3)
            print('kamu dibawa kerumah sakit')
            sleep(2)
            print('BAD ENDING :(')
            sleep(2)
    if(data == 1):
        print('\n\nBROOOOOOM.....')
        sleep(2)
        print('MOBIL YANG SANGAT KUAT!')
        sleep(2)
        print('Let..')
        sleep(2)
        print('Set....')
        sleep(2)
        print('GO ~> ~>')
        sleep(1)
        print('BOM!')
        sleep(1)
        print('BROOOOOOM')
        sleep(2)
        print('Ckiit ada mobil di depan!')
        sleep(2)
        print('dia habis menyelip mu!')
        sleep(2)
        print('WAKTUNYA PEMBALASAN')
        sleep(2)
        data = input('kamu mau nyelip dari kanan\natau TABRAK AJALAH? t/k')
        sleep(2)
        if(data == 't'):
            print("KAMU PUN TROBOS AJALAH")
            sleep(2)
            print('Mobil di depan pun TERLEMPAR')
            sleep(2)
            print('kamu pun menempati posisi pertama karena mobil lain pada minggir')
            sleep(2)
            print('KAMU AKHIRNYA MELiHAT GARIS FINISH DAN....')
            sleep(2)
            print('KAMU MENANG YEE')
            sleep(2)
            print('GOOD ENDING :D')
            sleep(2)
        if(data == 'k'):
            print('Kamu belok kekana dan berusaha menyelip')
            sleep(2)
            print('astaghfirullah. msuhnya  malah ngegas cok')
            sleep(2)
            print('kamu gak bisa nyelip dan sialnya di depan sudah ada garis finish :(')
            sleep(2)
            print('BAD ENDING :C')
if(data == 'n'):
    print("Keluar...")
    sleep(2)
        